spring:
  data:
    cassandra:
      keyspace-name: main
      username: jxBdKxaZuFvYnjktNSjSfyKN
      password: ikzm9-r-0_lPBWtxrMu6.LvflpyRaHiD0nA-2gMNl_O_cEyt1+ISWH4TgqxPz111Hp6A9EzCbXZe5Q,7f6bgbAsA8D9xZoJw0ZMtmeTb9-m-yj3QjKferYTLwL1qSc69
      schema-action: recreate
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  application:
    name: betterreads-data-loader
  main:
    allow-circular-references: true

datadump.location:
  author: src/main/resources/test-authors.txt
  works: src/main/resources/test-works.txt

datastax.astra:
  secure-connect-bundle: secure-connect-betterreads.zip

astra.db:
  id: b63c8387-9592-4499-8130-647da1d21407-1
  region: asia-south1
  keySpace: main
  application.token: AstraCS:jxBdKxaZuFvYnjktNSjSfyKN:f5c345090006d59d901f5e1d78f824337fa52a0c56f431d6d8e8f6c05260c6bf


